### PR TITLE
Apple Silicon - M1 - added darwin-arm64 platform, version bump 1.2.0

### PR DESCRIPTION
**Pull request by Beekiper**

### CODE REVIEW

**Comment by Beekiper** [comment]
Solves https://github.com/SavageCore/node-ffprobe-installer/issues/141

**Comment by SavageCore** [comment]
Thanks for this, please fix lint errors and undo your package name changes.

**Comment by SavageCore** [comment]
Also add binary source to readme

**Comment by SavageCore** [comment]
Closing due to changes not being made

**Comment by SavageCore** [comment]
@Beekiper where did you get these builds? It's my understanding the Homebrew builds aren't statically linked and can't see another source.

**Comment by TheRav3n** [comment]
@Lion7de This is what you are looking for: https://www.npmjs.com/package/node-ffprobe-installer

**Pull request closed without merging**
