### PR TITLE
added linux-arm

### PR DESCRIPTION
**Pull request by SNRSE**
i added the specifc build from the website you used

### CODE REVIEW

**Comment by SavageCore** [comment]
Looks good thanks, can you add the source and version to readme?

**Comment by SNRSE** [comment]
i added it to the readme. But i am not sure if I did it right. Please correct me if I did it wrong.

**Comment by SavageCore** [comment]
Great thanks

**Comment by SavageCore** [comment]
@all-contributors please add @SNRSE for 💻

**Comment by SavageCore** [comment]
@all-contributors please add @SNRSE for code

**Pull request merged**
