### PR TITLE
Fix darwin-arm64 platform, remove libxcb dependency

### PR DESCRIPTION
**Pull request by wongyiuhang**
#200
> Works great if `brew install ffpmeg` or `brew uninstall ffmpeg` gets executed
> 
> Only problem is if Homebrew gets uninstall or if `brew install ffpmeg` has never been executed prior
> 
> Error
> 
> ```
> dyld[89086]: Library not loaded: /opt/homebrew/opt/libxcb/lib/libxcb.1.dylib
>   Referenced from: /Users/mohamedbakoush/Documents/GitHub/node-ffprobe-installer/platforms/darwin-arm64/ffprobe
>   Reason: tried: '/opt/homebrew/opt/libxcb/lib/libxcb.1.dylib' (no such file), '/usr/local/lib/libxcb.1.dylib' (no such file), '/usr/lib/libxcb.1.dylib' (no such file)
> ```

As discussed and tested with @MohamedBakoush. The ffprobe for darwin-arm64 has been re-compiled again with removing external libxcb dependency.

### CODE REVIEW

**Comment by wongyiuhang** [comment]
Here's a doc for future on how to re-build ffprobe without `libxcb`

[Build Independent ffprobe on macOS](https://gist.github.com/wongyiuhang/d207aaf554e1985dd283a2fa1df949af)

**Comment by Kikobeats** [comment]
Thanks a lot!

**Comment by Kikobeats** [comment]
v1.4.0 published 🎉

**Comment by SavageCore** [comment]
> v1.4.0 published 🎉

Thank you, Kiko!

**Comment by MohamedBakoush** [comment]
I tried `npm i @ffprobe-installer/ffprobe` v1.4.0 and it didnt work, when i checked the SHA1 hash it was `1dd6aab8b1880c44cc98db96f950634ad701848a` (old version) while its seposed to be `384491447b76b483cfd32c99e9f6327f201e19a3` makeing me think darwin-arm64 binaries didn't get published to NPM.

While a new version of this repo can be seen at https://www.npmjs.com/package/@ffprobe-installer/ffprobe/v/1.4.0

https://www.npmjs.com/package/@ffprobe-installer/darwin-arm64 has not been updated.

Looking at previous commits - example from v1.2.0 https://github.com/SavageCore/node-ffprobe-installer/commit/9c730ff53ade4125993a0b194b905e5e961f23db and https://github.com/SavageCore/node-ffprobe-installer/commit/6d643168c262d993cabeaceb86795180f5b34b77, it seems new version number needs to be given to 
- darwin-arm64 [`package.json`](https://github.com/SavageCore/node-ffprobe-installer/blob/master/platforms/darwin-arm64/package.json) `version`
- Main [`package.json`](https://github.com/SavageCore/node-ffprobe-installer/blob/master/package.json)  `optionalDependencies` `@ffprobe-installer/darwin-arm64` 

for the new `384491447b76b483cfd32c99e9f6327f201e19a3` FFprobe binary to get published 

**If am wrong and NPM just needs time please ignore**

**Pull request merged**
